### ISSUE TITLE
CSS text decoration

### ISSUE THREAD

**Issue by ondoheer** [elcoach290/html5-manualdeconsulta#9]
en elejemplos como el primero, es mejor usar `a` que un classname, ya que en principiantes no se entiende el ejemplo. Estas ahorrando texto de explicación usando classnames y funciona genial para gente que ya sabe, pero para los que están aprendiendo puede generar más confusión

```css
.post__link{
  text-decoration: none; /* quita subrayado */
}

.post__price{
  text-decoration:line-through; /* agrega una línea horizontal
  a la mitad del texto  a modo de tachado */
}

.post__category{
  text-decoration: underline; /* subraya el texto */
}
```
